### ISSUE TITLE
[Bug] 称号物品 Type 疑似无法使用高版本物品 (1.17+?)

### ISSUE THREAD

**Issue by Yurinann** [CarmJos/UserPrefix#10]
### **问题简述**
称号物品 Type 疑似无法使用高版本物品 (1.17+?)

### **问题来源**
描述一下通过哪些操作才发现的问题，如：
1. 设置物品 type: AMETHYST_SHARD (紫水晶碎片), 又尝试了 RAW_GOLD (粗金)
2. 无法正常显示，后台报错。部分常用物品，如低版本即有的煤炭无影响。

### **问题截图/问题报错**
```
[20:44:36 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.IllegalArgumentException: Material cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:86) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:74) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:512) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor220.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:48) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
        at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:27) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:158) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:115) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:304) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at cc.carm.plugin.userprefix.model.ConfiguredPrefix.<init>(ConfiguredPrefix.java:41) ~[UserPrefix-2.4.1.jar:?]
        at cc.carm.plugin.userprefix.manager.PrefixManager.loadConfiguredPrefixes(PrefixManager.java:65) ~[UserPrefix-2.4.1.jar:?]
        at cc.carm.plugin.userprefix.manager.PrefixManager.loadPrefixes(PrefixManager.java:36) ~[UserPrefix-2.4.1.jar:?]
        at cc.carm.plugin.userprefix.command.UserPrefixAdminCommand.onCommand(UserPrefixAdminCommand.java:46) ~[UserPrefix-2.4.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[pufferfish-1.18.1.jar:git-Pufferfish-46]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:860) ~[pufferfish-1.18.1.jar:git-Pufferfish-46]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:510) ~[pufferfish-1.18.1.jar:git-Pufferfish-46]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[pufferfish-1.18.1.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1476) ~[pufferfish-1.18.1.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1266) ~[pufferfish-1.18.1.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-46]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### **操作环境**
Checking version, please wait...
[20:47:54 INFO]: This server is running Pufferfish version git-Pufferfish-46 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 434f1eb on HEAD)
You are running 1 version beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.

### **其他补充**
暂无

**Comment by CarmJos** [comment]
您好，这是因为UserPrefix未指定API版本导致的，请下载安装 [runs@1869357934](https://github.com/CarmJos/UserPrefix/actions/runs/1869357934) 后帮助测试，谢谢！

**Comment by Yurinann** [comment]
看起来还是不行）

> 您好，这是因为UserPrefix未指定API版本导致的，请下载安装 [runs@1869357934](https://github.com/CarmJos/UserPrefix/actions/runs/1869357934) 后帮助测试，谢谢！

**Comment by Yurinann** [comment]
另外，指定 api-version 可能会导致低于相应版本时无法加载？之前这样有一点印象，但是记不太清了。

**Comment by CarmJos** [comment]
感谢来自 @Ghost-chu 的贡献！请您下载 [runs@1871790253](https://github.com/CarmJos/UserPrefix/actions/runs/1871790253) 构建产物帮助测试，谢谢！

**Comment by Yurinann** [comment]
问题已解决，感谢您的帮助。

**Comment by Yurinann** [comment]
```
[15:59:19 INFO]: [UserPrefix] Successfully loaded default prefix 默认前缀
[15:59:19 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack cc.carm.plugin.userprefix.wrapper.ItemStackWrapper.deserialize(java.util.Map)' of class cc.carm.plugin.userprefix.wrapper.ItemStackWrapper for deserialization
java.lang.IllegalArgumentException: 物品 INK_SACK 不存在
        at cc.carm.plugin.userprefix.wrapper.ItemStackWrapper.deserialize(ItemStackWrapper.java:36) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) ~[patched_1.16.5.jar:git-Paper-794]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229) ~[patched_1.16.5.jar:git-Paper-794]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.5.jar:git-Paper-794]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479) ~[patched_1.16.5.jar:git-Paper-794]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.16.5.jar:git-Paper-794]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460) ~[patched_1.16.5.jar:git-Paper-794]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.16.5.jar:git-Paper-794]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229) ~[patched_1.16.5.jar:git-Paper-794]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.5.jar:git-Paper-794]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173) ~[patched_1.16.5.jar:git-Paper-794]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157) ~[patched_1.16.5.jar:git-Paper-794]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.16.5.jar:git-Paper-794]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.5.jar:git-Paper-794]
        at cc.carm.plugin.userprefix.util.ConfigurationUtil.bang(ConfigurationUtil.java:28) ~[?:?]
        at cc.carm.plugin.userprefix.model.ConfiguredPrefix.<init>(ConfiguredPrefix.java:42) ~[?:?]
        at cc.carm.plugin.userprefix.manager.PrefixManager.loadConfiguredPrefixes(PrefixManager.java:65) ~[?:?]
        at cc.carm.plugin.userprefix.manager.PrefixManager.loadPrefixes(PrefixManager.java:36) ~[?:?]
        at cc.carm.plugin.userprefix.command.UserPrefixAdminCommand.onCommand(UserPrefixAdminCommand.java:46) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

似乎因此出现了新问题：Paper 1.16.5 (Low Version?) 默认配置加载前缀时的报错。
@CarmJos @Ghost-chu

**Comment by CarmJos** [comment]
高版本已经没有墨囊这个物品了，每一个燃料都有独立的物品名称。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月23日(周三) 下午4:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CarmJos/UserPrefix] [Bug] 称号物品 Type 疑似无法使用高版本物品 (1.17+?) (Issue #10)




 [15:59:19 INFO]: [UserPrefix] Successfully loaded default prefix 默认前缀 [15:59:19 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack cc.carm.plugin.userprefix.wrapper.ItemStackWrapper.deserialize(java.util.Map)' of class cc.carm.plugin.userprefix.wrapper.ItemStackWrapper for deserialization java.lang.IllegalArgumentException: 物品 INK_SACK 不存在         at cc.carm.plugin.userprefix.wrapper.ItemStackWrapper.deserialize(ItemStackWrapper.java:36) ~[?:?]         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]         at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]         at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[patched_1.16.5.jar:git-Paper-794]         at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[patched_1.16.5.jar:git-Paper-794]         at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[patched_1.16.5.jar:git-Paper-794]         at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) ~[patched_1.16.5.jar:git-Paper-794]         at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229) ~[patched_1.16.5.jar:git-Paper-794]         at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.5.jar:git-Paper-794]         at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479) ~[patched_1.16.5.jar:git-Paper-794]         at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.16.5.jar:git-Paper-794]         at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460) ~[patched_1.16.5.jar:git-Paper-794]         at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.16.5.jar:git-Paper-794]         at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.16.5.jar:git-Paper-794]         at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229) ~[patched_1.16.5.jar:git-Paper-794]         at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.5.jar:git-Paper-794]         at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173) ~[patched_1.16.5.jar:git-Paper-794]         at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157) ~[patched_1.16.5.jar:git-Paper-794]         at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.16.5.jar:git-Paper-794]         at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.16.5.jar:git-Paper-794]         at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.5.jar:git-Paper-794]         at cc.carm.plugin.userprefix.util.ConfigurationUtil.bang(ConfigurationUtil.java:28) ~[?:?]         at cc.carm.plugin.userprefix.model.ConfiguredPrefix.<init&gt;(ConfiguredPrefix.java:42) ~[?:?]         at cc.carm.plugin.userprefix.manager.PrefixManager.loadConfiguredPrefixes(PrefixManager.java:65) ~[?:?]         at cc.carm.plugin.userprefix.manager.PrefixManager.loadPrefixes(PrefixManager.java:36) ~[?:?]         at cc.carm.plugin.userprefix.command.UserPrefixAdminCommand.onCommand(UserPrefixAdminCommand.java:46) ~[?:?]         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-794]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-794]         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-794]         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788) ~[patched_1.16.5.jar:git-Paper-794]         at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470) ~[patched_1.16.5.jar:git-Paper-794]         at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437) ~[patched_1.16.5.jar:git-Paper-794]         at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]         at java.lang.Thread.run(Thread.java:831) [?:?]  
似乎因此出现了新问题：Paper 1.16.5 (Low Version?) 默认配置加载前缀时的报错。
 @CarmJos @Ghost-chu
 
&mdash;

**Comment by Yurinann** [comment]
https://github.com/CarmJos/UserPrefix/blob/774e9b764e95a2e209c587232ce66ce48cd3ccc2/src/main/resources/prefixes/example-prefix.yml#L65

此处是否应该有所处理？
在 1.16.5 时，墨囊的物品 ID 为 minecraft:ink_sac。

**Comment by CarmJos** [comment]
我已在"关于物品序列化"的介绍中提到过相关问题以及解释。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月23日(周三) 下午5:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CarmJos/UserPrefix] [Bug] 称号物品 Type 疑似无法使用高版本物品 (1.17+?) (Issue #10)




 
https://github.com/CarmJos/UserPrefix/blob/774e9b764e95a2e209c587232ce66ce48cd3ccc2/src/main/resources/prefixes/example-prefix.yml#L65
 
此处是否应该有所处理？
 在 1.16.5 时，墨囊的物品 ID 为 minecraft:ink_sac。

**Comment by Yurinann** [comment]
好的，感谢帮助。
