### ISSUE TITLE
最新版好像用不了【？】

### ISSUE THREAD

**Issue by Coquettishpig** [CarmJos/UserPrefix#22]
```text
[18:22:48 ERROR]: Could not load 'plugins\UserPrefix-3.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: class cc.carm.plugin.userprefix.lib.easyplugin.EasyPlugin overrides final method isInitialized.()Z
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.VerifyError: class cc.carm.plugin.userprefix.lib.easyplugin.EasyPlugin overrides final method isInitialized.()Z
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_301]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_301]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_301]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_301]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_301]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_301]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_301]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_301]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_301]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_301]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_301]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 6 more
```

**Comment by CarmJos** [comment]
正在修复，见  https://github.com/CarmJos/EasyPlugin/releases/tag/1.4.9 。

**Comment by Coquettishpig** [comment]
> 

thanks！

**Comment by CarmJos** [comment]
您好，请下载 https://github.com/CarmJos/UserPrefix/actions/runs/2596100274 中的构件，以协助我进行测试，谢谢！

**Comment by CarmJos** [comment]
您好，请下载 https://github.com/CarmJos/UserPrefix/actions/runs/2596119252 对应构件并测试，以协助我解决该问题，谢谢！

**Comment by CarmJos** [comment]
已重新发版，见 https://github.com/CarmJos/UserPrefix/releases/tag/3.0.0 。
