### ISSUE TITLE
好像还有问题？主命令报错

### ISSUE THREAD

**Issue by Coquettishpig** [CarmJos/UserPrefix#24]
[19:21:56 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'userprefix' in plugin UserPrefix v3.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [?:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [?:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_301]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_301]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/inventory/meta/Damageable
        at cc.carm.plugin.userprefix.lib.easyplugin.utils.ItemStackFactory.setDurability(ItemStackFactory.java:53) ~[?:?]
        at cc.carm.plugin.userprefix.lib.easyplugin.gui.configuration.GUIItemConfiguration.setupItems(GUIItemConfiguration.java:40) ~[?:?]
        at cc.carm.plugin.userprefix.ui.PrefixSelectGUI.lambda$loadBackButton$0(PrefixSelectGUI.java:39) ~[?:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_301]
        at cc.carm.plugin.userprefix.ui.PrefixSelectGUI.loadBackButton(PrefixSelectGUI.java:39) ~[?:?]
        at cc.carm.plugin.userprefix.ui.PrefixSelectGUI.<init>(PrefixSelectGUI.java:30) ~[?:?]
        at cc.carm.plugin.userprefix.ui.PrefixSelectGUI.open(PrefixSelectGUI.java:100) ~[?:?]
        at cc.carm.plugin.userprefix.command.UserCommand.onCommand(UserCommand.java:18) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 15 more

**Comment by Coquettishpig** [comment]
![image](https://user-images.githubusercontent.com/107100449/176885353-71a865f0-dfba-439a-94a1-33e27f0ea9fa.png)
但是这个是好的

**Comment by CarmJos** [comment]
您好，请下载本构件帮助测试，谢谢。
[Desktop.zip](https://github.com/CarmJos/UserPrefix/files/9028714/Desktop.zip)

**Comment by Coquettishpig** [comment]
> 

ok

**Comment by Coquettishpig** [comment]
此版本功能我测试一切正常

**Comment by CarmJos** [comment]
感谢您的协助，我将在稍后重新发版。
