### ISSUE TITLE
[BUG] on-name-prefix 功能疑似在 Paper 1.20.5+上损坏

### ISSUE THREAD

**Issue by YuanYuanOwO** [CarmJos/UserPrefix#52]
### **问题简述**
on-name-prefix功能开启时，切换称号，玩家客户端掉线并`网络协议错误`

### **问题来源**
(?) 不确定 可能是Paper的问题？ 关掉on-name-prefix功能就不会掉线了

### **预期结果**(可选)
正常切换称号，且客户端不掉线

### **问题截图/问题报错**
```
[18:50:49] [Render thread/INFO]: Connecting to 127.0.0.1, 25565
[18:50:50] [Render thread/INFO]: [System] [CHAT] [XConomy]Found new version 2.26.3
[18:50:50] [Render thread/INFO]: [System] [CHAT] [XConomy]https://www.spigotmc.org/resources/xconomy.75669/
[18:50:50] [Render thread/INFO]: [System] [CHAT] Daylight_Yuan加入了游戏
[18:50:50] [Render thread/INFO]: Loaded 18 advancements
[18:50:53] [Render thread/INFO]: [System] [CHAT] 您选择了 默认前缀 作为当前显示的前缀。
[18:50:53] [Render thread/ERROR]: Failed to handle packet afv@26fee400
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team '998bdcb427d-e'.
	at ewx.b(SourceFile:308) ~[1.20.6-yb.jar:?]
	at fxy.a(SourceFile:2044) ~[1.20.6-yb.jar:?]
	at afv.a(SourceFile:132) ~[1.20.6-yb.jar:?]
	at afv.a(SourceFile:18) ~[1.20.6-yb.jar:?]
	at zz.a(SourceFile:25) ~[1.20.6-yb.jar:?]
	at bpm.d(SourceFile:162) [1.20.6-yb.jar:?]
	at bpq.d(SourceFile:23) [1.20.6-yb.jar:?]
	at bpm.A(SourceFile:136) [1.20.6-yb.jar:?]
	at bpm.bA(SourceFile:121) [1.20.6-yb.jar:?]
	at ffh.c(SourceFile:1275) [1.20.6-yb.jar:?]
	at ffh.f(SourceFile:888) [1.20.6-yb.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:265) [1.20.6-yb.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
[18:50:53] [Render thread/WARN]: Client disconnected with reason: 网络协议错误
```

### **操作环境**
```
> version
[18:59:21 INFO]: Checking version, please wait...
[18:59:23 INFO]: This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
```

### **其他补充**
此问题似乎无法100%复现，也可能是已知问题（
BungeeCord环境下的服务器似乎正常，不确定是不是环境原因

**Comment by CarmJos** [comment]
目测是有插件对队伍有修改，建议关闭，换用其他前缀显示插件。

**Comment by YuanYuanOwO** [comment]
经测试是与 Citizens 有冲突，问题为偶发性
