### ISSUE TITLE
前缀无效

### ISSUE THREAD

**Issue by Hzm20** [CarmJos/UserPrefix#55]
### **问题简述**

加载插件之后，自带的pro前缀无法加载，其他也不行
### **问题截图/问题报错**

[20:41:52] [Server thread/INFO]: [UserPrefix] 加载插件配置...
[20:41:53] [Server thread/INFO]: [UserPrefix] 加载前缀配置...
[20:41:53] [Server thread/INFO]: [UserPrefix] [ERROR] 在加载前缀 /home/container/plugins/UserPrefix/prefixes/example-prefix.yml 时出错，请检查配置！
[20:41:53] [Server thread/INFO]: [UserPrefix] [ERROR] Error occurred when loading prefix #/home/container/plugins/UserPrefix/prefixes/example-prefix.yml !
[20:41:53] [Server thread/WARN]: java.lang.IllegalArgumentException: NETHER_PORTAL isn't an item
[20:41:53] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.of(ItemStack.java:58)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.lib.xseries.XItemStack.deserialize(XItemStack.java:381)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.manager.PrefixManager.readItem(PrefixManager.java:159)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.manager.PrefixManager.addPrefix(PrefixManager.java:142)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.manager.PrefixManager.loadConfiguredPrefixes(PrefixManager.java:62)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.manager.PrefixManager.loadPrefixes(PrefixManager.java:32)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.Main.initialize(Main.java:44)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.lib.easyplugin.EasyPlugin.onEnable(EasyPlugin.java:71)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[20:41:53] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[20:41:53] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:644)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:593)
[20:41:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:752)
[20:41:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:511)
[20:41:53] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:333)
[20:41:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[20:41:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[20:41:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[20:41:53] [Server thread/INFO]: [UserPrefix] [ERROR] 在加载前缀 /home/container/plugins/UserPrefix/prefixes/xyg.yml 时出错，请检查配置！
[20:41:53] [Server thread/INFO]: [UserPrefix] [ERROR] Error occurred when loading prefix #/home/container/plugins/UserPrefix/prefixes/xyg.yml !
[20:41:53] [Server thread/WARN]: java.lang.IllegalArgumentException: NETHER_PORTAL isn't an item
[20:41:53] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.of(ItemStack.java:58)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.lib.xseries.XItemStack.deserialize(XItemStack.java:381)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.manager.PrefixManager.readItem(PrefixManager.java:159)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.manager.PrefixManager.addPrefix(PrefixManager.java:142)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.manager.PrefixManager.loadConfiguredPrefixes(PrefixManager.java:62)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.manager.PrefixManager.loadPrefixes(PrefixManager.java:32)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.Main.initialize(Main.java:44)
[20:41:53] [Server thread/WARN]: 	at UserPrefix-3.2.3.jar//cc.carm.plugin.userprefix.lib.easyplugin.EasyPlugin.onEnable(EasyPlugin.java:71)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[20:41:53] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[20:41:53] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:644)
[20:41:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:593)
[20:41:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:752)
[20:41:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:511)
[20:41:53] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:333)
[20:41:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[20:41:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[20:41:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[20:41:53] [Server thread/INFO]: [UserPrefix]    成功加载了 0 个前缀配置。
### **操作环境**

[17:23:57 信息］: Checking version, ple ase wait...
[17:23:59 信息］: This server is runnin g Leaves version 1.21.1-57-master@3436062 (2024-09-08T18:22:31Z) (Implementi ng API version 1.21.1-R0.1-SNAPSHOT)You are 6 version(s) behind
Download the new version at: https://1eavesmc.org/downloads/leaves Previous version: 1.21-46-c19e742 (MC:1.21)

**Comment by CarmJos** [comment]
见 [项目介绍/版本支持问题](https://github.com/CarmJos/UserPrefix?tab=readme-ov-file#1-%E7%89%88%E6%9C%AC%E6%94%AF%E6%8C%81%E9%97%AE%E9%A2%98) 。

**Comment by CarmJos** [comment]
抱歉，刚刚确认了下问题，可以麻烦您 [下载并安装此构件](https://github.com/CarmJos/UserPrefix/actions/runs/11054499231/artifacts/1982862034) 以测试问题是否解决吗？

**Comment by Hzm20** [comment]
解决了

**Comment by Hzm20** [comment]
发现不能应用于玩家身上，虽然给了，但是没用

**Comment by CarmJos** [comment]
那应该是使用上有问题哦~

**Comment by Hzm20** [comment]
用pro也不行

**Comment by Hzm20** [comment]
真的

**Comment by CarmJos** [comment]
什么叫“不行”？

**Comment by Hzm20** [comment]
![Image_1727436390623](https://github.com/user-attachments/assets/82bad505-78c3-4ec7-ac6a-b978dcd20a65)

**Comment by Hzm20** [comment]
这就叫不行

**Comment by CarmJos** [comment]
看看配置文件

**Comment by Hzm20** [comment]
[config.txt](https://github.com/user-attachments/files/17163442/config.txt)

**Comment by CarmJos** [comment]
```yaml

# 功能设定
functions:
  # 自动使用前缀，即当玩家没有自己选择一个前缀的时候，会自动使用所拥有的的前缀中权重最高的那一个
  auto-prefix-use: true
  # 头顶与TabList前缀功能，该方法用到了玩家名计分板接口，如有冲突请关掉哦~
  on-name-prefix:
    # 是否开启本功能
    enable: true
    # 是否按降序排列，即权重越高的前缀显示在越上面；若为false则按升序排列。
    order-desc: true
  # 聊天功能设定
  # - 我不推荐使用本插件的聊天功能，而是建议使用其他的聊天插件。
  # - 本插件仅仅提供了**最基本**的格式变量支持，不包含其他任何功能。
  # - 注意聊天格式需要遵守Bukkit原格式，即不得缺失 “%1$s” 和 “%2$s” 。
  # - 本插件的聊天功能不影响其他插件对聊天事件的操作。
  chat:
    # 是否开启本功能
    enable: false
    # 聊天的格式，注意 “%1$s” 和 “%2$s” 不可缺少。
    # - %1$s -> 玩家名
    # - %2$s -> 聊天内容
    format: <%1$s> %2$s

```

都没有开启这个选项，如何有用呢？

使用前请详阅配置文件内容，描述问题时请一个问题一个议题，此议题不在回复。
