### ISSUE TITLE
[Bug] Paper 启动服务器时插件报错

### ISSUE THREAD

**Issue by Yurinann** [CarmJos/UserPrefix#8]
### **问题简述**
启动服务器时插件报错

### **问题来源**
1. 启动服务器
2. 报错出现

### **预期结果**(可选)
插件正常加载

### **问题截图/问题报错**
```
[18:25:09 ERROR]: Could not load 'plugins\UserPrefix-2.4.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bstats/charts/CustomChart
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/bstats/charts/CustomChart
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Paper-794]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.bstats.charts.CustomChart
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Paper-794]
        ... 7 more
```

### **操作环境**
```
[18:26:49 INFO]: Checking version, please wait...
[18:26:50 INFO]: [BentoBox] Successfully downloaded data from GitHub.
[18:26:50 INFO]: This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```
1.18.1 Pufferfish (Paper fork) 相同

### **其他补充**
暂无

**Comment by CarmJos** [comment]
正在排查问题。

**Comment by CarmJos** [comment]
不会吧...  我用不用的反编译软件检查了类的导用都是正常的地址呀？
### 调用过程
#### 主类上的调用
![image](https://user-images.githubusercontent.com/36306882/154485779-b91015b9-5b46-4ec3-b7b0-d4e36d991f64.png)

#### 调用导入地址

![image](https://user-images.githubusercontent.com/36306882/154485836-21e47b9b-1482-4bcc-91a2-357a2c95d93e.png)


#### 相关包内类
![image](https://user-images.githubusercontent.com/36306882/154485921-a9ed345c-c1cc-4d33-be2e-7862a300705f.png)

**Comment by CarmJos** [comment]
您好，我不能复现您出现的问题：

环境为 Purpur `git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

![image](https://user-images.githubusercontent.com/36306882/154487783-17bdb1a3-3d03-47e1-a709-b70e9a902b19.png)

**Comment by Ghost-chu** [comment]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/30802565/154488033-d018c70b-6410-4f65-a581-6c80027801f5.png">
问题无法复现，请上传你下载的JAR

**Comment by Yurinann** [comment]
https://cowtransfer.com/s/f58c9eeae09049

Paper 1.16.5

另外，我使用的环Java 境是 Azul Zulu 16 (1.18.1 时为 17)

**Comment by CarmJos** [comment]
ummm...

我觉得他的意思是上传插件的jar。

**Comment by Yurinann** [comment]
https://cowtransfer.com/s/1cbe691d14ee4b

来源于 Github Actions

**Comment by CarmJos** [comment]
Github Actions 相关构建已被标注 “Build & Tests” 即构建仅用于测试，并不能用于生产环境。

**Comment by CarmJos** [comment]
为避免类似情况的发生，自 [**81e0c09**](https://github.com/CarmJos/UserPrefix/commit/81e0c0960fc73fa968d5efc31b6c73f5f5d4b550) 开始，测试流水线将同时提供“测试产物”与“最终产物”，如 [`runs@1858955419`](https://github.com/CarmJos/UserPrefix/actions/runs/1858955419)

**Comment by CarmJos** [comment]
同时强烈建议使用 **releases** 下的插件版本。

**Comment by CarmJos** [comment]
如问题已解决，请关闭本 issues 。感谢您对社区的贡献。

**Comment by Yurinann** [comment]
问题已解决，感谢您的及时帮助。
