### ISSUE TITLE
[Bug] 玩家在非正常离开游戏(?)时会触发 UserDataRecalculateEvent 报错

### ISSUE THREAD

**Issue by Yurinann** [CarmJos/UserPrefix#9]
### **问题简述**
玩家在非正常离开游戏(不确定, 此处是由于未成功登录被 AuthMe 踢出)时会触发 UserDataRecalculateEvent 报错

### **问题来源**
描述一下通过哪些操作才发现的问题，如：
1. 玩家登录
2. 登录超时，被踢出游戏
3. 后台出现报错

### **预期结果**(可选)
如果问题不发生，应该是什么情况

### **问题截图/问题报错**
```
[15:11:35 INFO]: ThrillMe lost connection: [玩家系统] 错误的密码
[15:11:35 WARN]: [LuckPerms] Unable to pass event UserDataRecalculateEvent to handler cc.carm.plugin.userprefix.Main$$Lambda$7087/0x0000000802305788
java.lang.IllegalStateException: UserPrefixExpireEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:618) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at cc.carm.plugin.userprefix.manager.UserManager.checkPrefix(UserManager.java:124) ~[UserPrefix-2.4.0.jar:?]
        at cc.carm.plugin.userprefix.listener.processor.UserNodeUpdateProcessor.process(UserNodeUpdateProcessor.java:14) ~[UserPrefix-2.4.0.jar:?]
        at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:95) ~[?:?]
        at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:43) ~[?:?]
        at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107) ~[?:?]
        at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84) ~[?:?]
        at me.lucko.luckperms.common.event.EventDispatcher.post(EventDispatcher.java:128) ~[?:?]
        at me.lucko.luckperms.common.event.EventDispatcher.lambda$postAsync$0(EventDispatcher.java:143) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

### **操作环境**
[15:46:54 INFO]: Checking version, please wait...
[15:46:56 INFO]: This server is running Pufferfish version git-Pufferfish-46 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 434f1eb on HEAD)
You are on the latest version!

### **其他补充**
暂无

**Comment by CarmJos** [comment]
您好，问题已确认，请下载 [runs@1863862246](https://github.com/CarmJos/UserPrefix/actions/runs/1863862246) 帮助确认问题是否解决，谢谢！

**Comment by CarmJos** [comment]
> 

我更喜欢让一个事件固定为“同步事件”或“异步事件”，更便于其他开发者理解、使用。

**Comment by Yurinann** [comment]
```
[10:55:57 INFO]: Yurinann issued server command: /prefix
[10:55:57 WARN]: [LuckPerms] Unable to pass event UserDataRecalculateEvent to handler cc.carm.plugin.userprefix.Main$$Lambda$6602/0x0000000802332ea0
java.lang.IllegalStateException: InventoryCloseEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:612) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1470) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.EntityPlayer.closeInventory(EntityPlayer.java:1562) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:537) ~[patched_1.16.5.jar:git-Paper-794]
        at cc.carm.plugin.userprefix.listener.processor.UserNodeUpdateProcessor.process(UserNodeUpdateProcessor.java:17) ~[?:?]
        at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:95) ~[?:?]
        at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:43) ~[?:?]
        at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107) ~[?:?]
        at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84) ~[?:?]
        at me.lucko.luckperms.common.event.EventDispatcher.post(EventDispatcher.java:128) ~[?:?]
        at me.lucko.luckperms.common.event.EventDispatcher.lambda$postAsync$0(EventDispatcher.java:143) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

LuckPerms 5.4.5, Paper 1.16.5, 疑似本次修复的遗留问题。

**Comment by CarmJos** [comment]
您好，请下载 [runs@1953626170](https://github.com/CarmJos/UserPrefix/actions/runs/1953626170) 帮助测试，谢谢。

**Comment by CarmJos** [comment]
您下次遇见问题不要在已关闭的issues中回复，谢谢。@Yurinann

**Comment by Yurinann** [comment]
> 您下次遇见问题不要在已关闭的issues中回复，谢谢。@Yurinann

好的。Reopen Issue 的本意是将问题归为同类原因导致的结果，下次我会注意独立分清。

**Comment by CarmJos** [comment]
> 

主要是这种情况下我看不见通知，您下载一下构建测试吧。

**Comment by Yurinann** [comment]
> > 
> 
> 主要是这种情况下我看不见通知，您下载一下构建测试吧。

实装至目前暂未发现，故认为问题已解决，感谢您的及时帮助。
